### ISSUE TITLE
Elsewhere in regulatory documentation, python is restricted to 3.9, it should be restricted similarly here

### ISSUE THREAD

**Issue by sjswerdloff** [RadiotherapyAI/rai#66]
https://github.com/RadiotherapyAI/RadiotherapyAI/blob/affda9a647e298b38591c91c2a49f6450c804ab4/pyproject.toml#L9

**Comment by SimonBiggs** [comment]
Actually, we have two releases going on here. The open source tool (non-regulated) installable via pip from PyPI (which should be as permissive with versioning as possible), and then the end-point regulated product, which should be as pinned as possible. It is always up the person producing the final "Product" to explicitly pin the versions. As such, through the regulated documentation, I will be referring to the regulated pinned product. But, we will still be providing the non-regulated unrestricted library release.

For example, in the `pyproject.toml` file all of the versions are as lax as possible:

https://github.com/RadiotherapyAI/RadiotherapyAI/blob/affda9a647e298b38591c91c2a49f6450c804ab4/pyproject.toml#L10-L13

But, once the `SOUP` part is documented, it will actually refer to the exact version numbers that are utilised within CI and the regulated binary. These exact version numbers are locked down:

https://github.com/RadiotherapyAI/RadiotherapyAI/blob/f7ba4dd825934967037655c3dafaf823d7db608e/poetry.lock#L1658-L1664

**Comment by sjswerdloff** [comment]
Hmmm.
I'm not convinced, but if you are content that this will all work out in the described fashion, feel free to close

**Comment by SimonBiggs** [comment]
I'll take a better crack at convincing you tomorrow :slightly_smiling_face:. I'd prefer to attempt to convince at least before closing.

**Comment by SimonBiggs** [comment]
@sjswerdloff, just so that it is documented here, was the solution detailed over in https://github.com/RadiotherapyAI/rai/pull/69 sufficient to address your concerns here?

**Comment by sjswerdloff** [comment]
Yeah, all good.
The open source part is flexible, the regulated part is locked down.
You will need to consider your process for pulling updates to the open source side over to the regulated side, especially if you have breaking dependencies on update on the regulatory side.

But that is not a consideration for the open source side.
So... All good
